pipeline:
  terraform_validate:
    image: jmccann/drone-terraform:5
    tf_version: 0.14.8
    actions:
      - validate
  terraform_plan:
    image: jmccann/drone-terraform:5
    tf_version: 0.14.8
    actions:
      - plan
  terraform_apply:
    image: jmccann/drone-terraform:5
    tf_version: 0.14.8